services:
  api:
    build: .
    container_name: fraudshield_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - fraudshield_network

  postgres:
    image: postgres:16-alpine
    container_name: fraudshield_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: fraudshield_user
      POSTGRES_PASSWORD: fraudshield_password
      POSTGRES_DB: fraudshield_db
    ports:
      - "5432:5432"
    volumes:
      - fraudshield_postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    networks:
      - fraudshield_network

  redis:
    image: redis:7-alpine
    container_name: fraudshield_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - fraudshield_network

volumes:
  fraudshield_postgres_data:

networks:
  fraudshield_network:
    driver: bridge