/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as DashboardRiskAnalysisRouteImport } from './routes/dashboard.risk-analysis'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardTransactionsIdRouteImport } from './routes/dashboard.transactions.$id'
import { Route as DashboardReportsIdRouteImport } from './routes/dashboard.reports.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRiskAnalysisRoute = DashboardRiskAnalysisRouteImport.update({
  id: '/risk-analysis',
  path: '/risk-analysis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardTransactionsIdRoute = DashboardTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardTransactionsRoute,
} as any)
const DashboardReportsIdRoute = DashboardReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/reports': typeof DashboardReportsRouteWithChildren
  '/dashboard/risk-analysis': typeof DashboardRiskAnalysisRoute
  '/dashboard/transactions': typeof DashboardTransactionsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/transactions/$id': typeof DashboardTransactionsIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/reports': typeof DashboardReportsRouteWithChildren
  '/dashboard/risk-analysis': typeof DashboardRiskAnalysisRoute
  '/dashboard/transactions': typeof DashboardTransactionsRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/transactions/$id': typeof DashboardTransactionsIdRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/reports': typeof DashboardReportsRouteWithChildren
  '/dashboard/risk-analysis': typeof DashboardRiskAnalysisRoute
  '/dashboard/transactions': typeof DashboardTransactionsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/transactions/$id': typeof DashboardTransactionsIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/alerts'
    | '/dashboard/reports'
    | '/dashboard/risk-analysis'
    | '/dashboard/transactions'
    | '/dashboard/'
    | '/dashboard/reports/$id'
    | '/dashboard/transactions/$id'
    | '/dashboard/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/alerts'
    | '/dashboard/reports'
    | '/dashboard/risk-analysis'
    | '/dashboard/transactions'
    | '/dashboard'
    | '/dashboard/reports/$id'
    | '/dashboard/transactions/$id'
    | '/dashboard/admin'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/alerts'
    | '/dashboard/reports'
    | '/dashboard/risk-analysis'
    | '/dashboard/transactions'
    | '/dashboard/'
    | '/dashboard/reports/$id'
    | '/dashboard/transactions/$id'
    | '/dashboard/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/risk-analysis': {
      id: '/dashboard/risk-analysis'
      path: '/risk-analysis'
      fullPath: '/dashboard/risk-analysis'
      preLoaderRoute: typeof DashboardRiskAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/transactions/$id': {
      id: '/dashboard/transactions/$id'
      path: '/$id'
      fullPath: '/dashboard/transactions/$id'
      preLoaderRoute: typeof DashboardTransactionsIdRouteImport
      parentRoute: typeof DashboardTransactionsRoute
    }
    '/dashboard/reports/$id': {
      id: '/dashboard/reports/$id'
      path: '/$id'
      fullPath: '/dashboard/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteImport
      parentRoute: typeof DashboardReportsRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardReportsRouteChildren {
  DashboardReportsIdRoute: typeof DashboardReportsIdRoute
}

const DashboardReportsRouteChildren: DashboardReportsRouteChildren = {
  DashboardReportsIdRoute: DashboardReportsIdRoute,
}

const DashboardReportsRouteWithChildren =
  DashboardReportsRoute._addFileChildren(DashboardReportsRouteChildren)

interface DashboardTransactionsRouteChildren {
  DashboardTransactionsIdRoute: typeof DashboardTransactionsIdRoute
}

const DashboardTransactionsRouteChildren: DashboardTransactionsRouteChildren = {
  DashboardTransactionsIdRoute: DashboardTransactionsIdRoute,
}

const DashboardTransactionsRouteWithChildren =
  DashboardTransactionsRoute._addFileChildren(
    DashboardTransactionsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardReportsRoute: typeof DashboardReportsRouteWithChildren
  DashboardRiskAnalysisRoute: typeof DashboardRiskAnalysisRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardReportsRoute: DashboardReportsRouteWithChildren,
  DashboardRiskAnalysisRoute: DashboardRiskAnalysisRoute,
  DashboardTransactionsRoute: DashboardTransactionsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
